/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos.orders;

import pos.MainWindow;
import pos.products.Product;

/**
 *
 * @author ralph
 */
public class BasketPanel extends javax.swing.JPanel implements java.util.Observer {

    /**
     * Creates new form BasketPanel
     */
    public BasketPanel() {
        initComponents();
    }
    
    private MainWindow mainWindow;
    public BasketPanel(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
        initComponents();
        Basket basket = mainWindow.getBasket();
        basket.addObserver(this);
        update(basket, null);
    }
    
    @Override
    public void update(java.util.Observable o, Object arg) {
        orderlines.removeAll();
        Basket basket = (Basket) o;
        for (Product product : basket.getProducts()) {
            OrderLine line = new OrderLine(product, basket.getProductAmount(product));
            orderlines.add(line);
        }
        orderlines.add(javax.swing.Box.createVerticalGlue());
        price.setText(java.text.NumberFormat.getCurrencyInstance(java.util.Locale.GERMANY).format(basket.getTotalCosts() / 100.0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        orderlines = new javax.swing.JPanel();
        labelTotal = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();

        title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        title.setText("Basket");

        orderlines.setLayout(new javax.swing.BoxLayout(orderlines, javax.swing.BoxLayout.Y_AXIS));

        labelTotal.setText("Total:");

        price.setText("Price");

        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(price))
                    .addComponent(orderlines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(placeOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderlines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeOrderButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        mainWindow.showPanel(new OrderDetails(mainWindow));
    }//GEN-LAST:event_placeOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel orderlines;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JLabel price;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
