/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.admin;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.ImageRenderer;
import pos.MainWindow;
import pos.products.Supplier;

/**
 *
 * @author sander
 */
public class SupplierList extends javax.swing.JPanel {

    private final MainWindow mainWindow;

    /**
     * Creates new form SupplierList
     * @param mainWindow
     */
    public SupplierList(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
        initComponents();
        addSuppliers();
    }
    
    private void addSuppliers() {
        List<Supplier> suppliers = Supplier.findAll(mainWindow.getDbManager());
        DefaultTableModel model = (DefaultTableModel) supplierTable.getModel();
        for (Supplier supplier : suppliers) {
            model.addRow(new Object[]{supplier.getId(), supplier.getName()});
        }
    }
    
    public ImageRenderer getImageRenderer(){
        return new ImageRenderer();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        addSupplierBtn = new javax.swing.JButton();
        removeSupplierBtn = new javax.swing.JButton();
        editSupplierBtn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Naam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(supplierTable);
        if (supplierTable.getColumnModel().getColumnCount() > 0) {
            supplierTable.getColumnModel().getColumn(0).setMinWidth(0);
            supplierTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            supplierTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        addSupplierBtn.setText("Voeg Leverancier Toe");
        addSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierBtnActionPerformed(evt);
            }
        });

        removeSupplierBtn.setText("Verwijder Leveranier");
        removeSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSupplierBtnActionPerformed(evt);
            }
        });

        editSupplierBtn.setText("Bewerk Leverancier");
        editSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSupplierBtnActionPerformed(evt);
            }
        });

        backButton.setText("Terug");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editSupplierBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeSupplierBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSupplierBtn))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSupplierBtn)
                    .addComponent(removeSupplierBtn)
                    .addComponent(editSupplierBtn)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSupplierBtnActionPerformed
        int[] rows = supplierTable.getSelectedRows();
        boolean[] rowsToRemoveFromList = new boolean[rows.length];
        for (int rowNum = 0; rowNum < rows.length; rowNum++) {
            Object toRemoveId = supplierTable.getValueAt(rows[rowNum], 0);
            rowsToRemoveFromList[rowNum] = Supplier.remove(mainWindow.getDbManager(), toRemoveId);
        }
        //remove listed as true
        for (int i = rowsToRemoveFromList.length - 1; i >= 0; i--) {
            if (rowsToRemoveFromList[i]) {
                ((DefaultTableModel) supplierTable.getModel()).removeRow(rows[i]);
            }
        }
    }//GEN-LAST:event_removeSupplierBtnActionPerformed

    private void addSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierBtnActionPerformed
        //mainWindow.showPanel(new AddSupplier(mainWindow));
        mainWindow.showPanel(new AddSupplier(mainWindow));
    }//GEN-LAST:event_addSupplierBtnActionPerformed

    private void editSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSupplierBtnActionPerformed
        int[] rows = supplierTable.getSelectedRows();
        if(rows.length == 1){
           int id = (int)supplierTable.getValueAt(rows[0], 0);
           mainWindow.showPanel(new AddSupplier(mainWindow, id));
        }else if(rows.length < 1){
            JOptionPane.showMessageDialog(null, "Selecteer een supplier om te bewerken.");
        }else if(rows.length > 1){
            JOptionPane.showMessageDialog(null, "Er kan maximaal 1 supplier tegelijk bewerkt worden.");
        }
    }//GEN-LAST:event_editSupplierBtnActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        mainWindow.showPanel(new ProductList(mainWindow));
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplierBtn;
    private javax.swing.JButton backButton;
    private javax.swing.JButton editSupplierBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeSupplierBtn;
    private javax.swing.JTable supplierTable;
    // End of variables declaration//GEN-END:variables
}
