/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos.products;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.Box;
import pos.MainWindow;

/**
 *
 * @author ralph
 */
public class ProductList extends javax.swing.JPanel {

    private final MainWindow mainWindow;
    private final Category category;
    /**
     * Creates new form ProductList
     */
    public ProductList(MainWindow mainWindow, Category category) {
        this.mainWindow = mainWindow;
        this.category = category;
        initComponents();
        addProducts();
    }
    
    private void addProducts() {
        List<Product> prods = Product.findByCategory(category, mainWindow.getDbManager());
        for (final Product product : prods) {
            ProductItem productItem = new ProductItem(product);
            productItem.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    mainWindow.showPanel(new ProductDetails(mainWindow, product));
                }
            });
            products.add(productItem);
        }
        products.add(Box.createVerticalGlue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basket = new pos.orders.BasketPanel(mainWindow);
        productsScrollpane = new javax.swing.JScrollPane();
        products = new javax.swing.JPanel();

        products.setLayout(new javax.swing.BoxLayout(products, javax.swing.BoxLayout.Y_AXIS));
        productsScrollpane.setViewportView(products);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(basket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsScrollpane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(basket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 242, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pos.orders.BasketPanel basket;
    private javax.swing.JPanel products;
    private javax.swing.JScrollPane productsScrollpane;
    // End of variables declaration//GEN-END:variables
}
